### PR TITLE
Elev8 Evaluation of Cookies

### PR DESCRIPTION
**Pull request by jakesatcher**
Elev8 chose to evaluate team_WeAreScientists recipe. Photo of cookies, and team evaluation photo are supplied. Public key is below. 

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvXbeNmV29SWll5rBkzH1
Bcini3bjmckBfJj7+gGt5zMP7vpLaMKyl8rIEwj/2w30SAUAysMpxwZ6DpHUynL9
E9rgC8W/LqgHe4oMh+UyKQxj36kuf8YWT0q+kE5DBaZFg8Hb5aGoxF81lz3JlRq8
tPXMYih/5ajQSXrrp1CjpUtXJAhli5ixIXCDWoYiN8AzUImZPakCCOvm8Pq26zno
jAD5GS9bAaEpTj0gzzNNTVGlyvpdeYNbohHkvYZdI9m227IlPQ020VKS9JRw4F/N
s2u7mMWuX2BMWDGjijkhevu6HBr5DTv23EjP7/jayxPZHZ4KgVqZpMWlfLZjPK7O
BQIDAQAB
-----END PUBLIC KEY-----

### CODE REVIEW

**Comment by StevenVanAcker** [comment]
Those cookies look awesome!

UEX+zAKTDNURvLCYwqKZHv2pQLyBe2vvSqhYLdZw+mp1JAKAfzsF4NGx1Aprq17l4vKloGo5hwM2
0D+/NAxuMOpnV21ya03++wPerCVOM1JLDLTGNGdsh9oqFN/px90GF1kM9WMjlY4Lr1kO+DFVYrcS
jxtcuV6zASrRRayc6u6HPQNrETLRkUTrhGuCSpwpJR/1s+uKGO/uoxkiDIuRrAy+EVzp6sQbyOJr
sDyeq1CnaS/K5pdl8bJ4hkD0u5Se+kiX75RmFmJbaOJGvWaRYSyfGcb13tKSE6BrUV08cfoHRKdo
4LpSdv3NVbl5xYbsj8hTwXXyIW+Rw+gh1PKUgg==

**Comment by jakesatcher** [comment]
Hey Steven,

I can not get the flag decrypted. I don't know if there is something wrong
with it, or I'm just dumb, which is the likelier of the 2.

 RSA operation error
139910079370904:error:0407109F:rsa
routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error:rsa_pk1.c:273:
139910079370904:error:04065072:rsa routines:RSA_EAY_PRIVATE_DECRYPT:padding
check failed:rsa_eay.c:602:

**Comment by StevenVanAcker** [comment]
what commands are you executing?

**Comment by jakesatcher** [comment]
False alarm. It was a PICNIC error. It worked once we deleted the
carriage returns from the flag.

**Pull request merged**
