### PR TITLE
Made In MIM

### PR DESCRIPTION
**Pull request by jingle-jells**
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2J+58IAXKH8fpSi7G5kP
s1AzTyOn5ClxKADMUdCJjKz6l9Ir896P5CSRp+16jhqoiHYBPBQv1zrwW1Uu3Ugn
TwACiH0dpK0oF1YvvCBoTp9GZjNvqbaxb/pNaYgMsiIBZNH+umGYsKiV5Fetd28F
T248U480Lu7gHLSoAXGVFOLw2hd70/DG1XseIhmhRaf9uEPybl6SGrFaHCDZS0+7
IzRyqlLd8d7JxHkhgL648Gcdy+tHMrulo1r0BBA6Jo8PnG3OGYIKnL5pvgdf9ifN
J3hl655bp2vk39uQLKONlseOhq8BucuXpW9eVR13jMj4JWz1ESp2/LbBfsunmjIx
bQIDAQAB
-----END PUBLIC KEY-----

### CODE REVIEW

**Comment by StevenVanAcker** [comment]
judges ruling: looks like you just put whipped cream inside bought cookies, without producing any cookies, so not a valid entry for either team Brain or Brawn

**Comment by jingle-jells** [comment]
@StevenVanAcker ok, but still was fun and this new cookies are really awesome if you would try some

I will try doing better.

**Comment by jingle-jells** [comment]
@StevenVanAcker if you wanna have some fun time watch the video I prepared. I hope you like it.

**Comment by jingle-jells** [comment]
@StevenVanAcker could the cookies be baked without oven? I.e. on the pan (but actually no frying because the pan is only for heating it up, no additional oil will be needed).

**Pull request closed without merging**
